# Generated by Django 4.0.4 on 2023-08-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название блога')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Альт.название')),
                ('body', models.TextField(blank=True, null=True, verbose_name='контент')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='imagines/', verbose_name='изображение')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('views_count', models.IntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'блог',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='date_create',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modified_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='дата последнего изменения'),
        ),
    ]
